** CHAPTER 1 Des Bois
*** SECTION II Des Bois de France

Hornbeam must be well chosen to be good. The one that grows in damp soils is greasy, cottony or without consistency. It is whiter than the others; but this very whiteness is a sign by which we recognize it as being less good. The Hornbeam turns perfectly. Its pores, without being tight, are very fine: but by the very fact that they are loose, it is subject to splitting, unless it is partially dry. When it is still fresh, we make excellent screws of medium size, the threads of which cut very sharply and very cleanly. The tenons that we make for Hornbeam works are not safe, unless they have a certain size; They also make excellent mallets for the lathe and for carpentry, especially if you choose a knotty part. It is with this wood that cabinetmakers veneer the white squares of common checkerboards: the others are made with holly. We also make white fillets for marquetry. Finally, except for carpentry in buildings, wheelwrights and furniture, Hornbeam can be used for an infinity of pleasant works, with the choice that we have recommended.

THE ordinary WALNUT, fig. 7, is a tree common to almost all the provinces of France, and of the greatest utility in the arts. It comes very high and very big. He does not like in forests; he asks to be isolated, either on the main roads or in the fields. There are few woods as bonding as Walnut. It also supports tenon and mortise well. Furniture made from this wood is much stronger than that of concrete. It turns perfectly. It takes a fairly nice polish, either on the lathe or on the plane. As it produces tables of great width, your coach carpenters make car panels of the largest size from it. We turn it over the fire, following the curve of the box, heating it on one side and wetting it on the other. Before rosewood and acajon were so common in Europe, walnut was the wood from which the most precious furniture was made. It is true that then we commonly had Walnut full of veins and accidents which we opposed symmetrically, and which had the most beautiful effect, especially when on a gray-brown background, we saw large, almost black veins: but luxury, having multiplied the enjoyments, we hastened to cut down the trees before they had acquired, through age, this color and these veins which highlighted their beauty: today almost all the walnut trees are gray and barely veined. The sample shown in the figure is of this species; but our sole aim was that we could recognize the wood by its general characteristics, and especially by the grain or the bark. If the Walnut were more compact and harder than it is, it would be the king of the woods; but, in this case, the tenons would not be as solid, since their very compactness makes them brittle.

When the Walnut is reversed, as the workers say, or when it is wavy, it must be worked with a toothed plane, a standing plane or a two-iron plane.

Fig. 8 represents another species of Walnut, which grows particularly in Auvergne, and which must be preferred because it is the most beautiful, and rarely attacked by worms. The black veins that we see there are not accidents like in the old Walnut tree that we are talking about: they are its constituent characteristics. Its nature, its properties, are absolutely the same as those of the previous one. So, for such a slight difference, we will not stop to give a further description.

THE ASH TREE, fig. 9, is a large and superb forest tree, whose leaves closely resemble those of the elderberry or the yebule. The uses to which it is employed in the arts are quite good; but, as a reward, they are of the greatest importance. As this wood is the most binding of all, it never breaks sharply, but sorts for a long time before breaking, we make an infinity of works from it in which this property is extremely valuable. It is with duFi^e that we make strong axles for many cars which transport heavy Êudeaux. They are made into stretchers for carriage trains, post-chaises and cabriolets, chairs (and they are the best), excellent hammer handles, saw arms, and finally very high, very small ladders. , and yet very-s<Jides. Its bark is subject to being bitten by worms; but it is rare that they enter the wood. It is approximately the same colors as that of the hornbeam; but the latter is quite plain, whereas that of the Ash is a sort of rib. Ash is quite a beautiful white, not very dense: it takes stain well. It turns well and planes poorly: so we never use it in carpentry. To give, in a single word, a fair idea of ​​the strength and binder of the Ash, it is enough for us to say that, when the two corner stones of the pediment of the new Church of Sainte-Geneviève arrived, by water, at the port des Invalides, and it was a question of transporting them to their destination, the first was dragged by capstans, which lasted about three days and three nights: we did not dare put it on any car. Finally, for the second, a hand truck was built, made of a very large frame, armed in all directions with iron bars, and rolling on hubs, two feet or so in diameter, in place of wheels: the two axles There were two ash trees, and the ard was drawn by sixty-three horses. From this we will judge the enormity of the stone, and its weight. These axles were so little tired, that some time later the same car was used to transport the drone which had just been melted for the same Church, from the place where it was melted, to the Church for the beiùr, and then bring it back to the bottom of the tower.

THE CHESTNUT TREE, Fig. 1 Pl. 2, is a purely forest tree; we see few around Paria that have acquired a certain size and height; but there are several provinces of France where it comes with the greatest beauty. This wood was once widely used for framing. It is claimed that worms and spiders do not attack it. All the attics of ancient monuments are made of this wood; or it is no longer used in Paris, probably because we have neglected its cultivation in high forests, because we find a lot of it there. coppice, and even of medium size in forests. The caterpillars almost never attack it: so the Chattaigniers are always furnished with their leaves. Its wood is very bondable. It even seemed, at least as much as the ash tree. It would be desirable that we try to use it for chairs, instead of alder, which is used in common places, for no other reason than its lightness. It is true that being a little wave of pain, it took the dye less well than ash, which is very white. This wood is used very little in the arts; and, as it is not allowed to grow for more than five or ten years, it is used very usefully to make excellent hoops, weaving and other objects of little consequence.

THE WILLOW, fig. 2, is almost of no use in the arts. There is no one who does not know it on its feet, to enjoy itself at the edge of the bushes, in aquatic and low places: its branches, which are cut every two years, give good use hoops; but they are not worth the chestnut. We also make stakes in certain provinces, in the absence of other wood; but, as this wood is very soft, it rots quickly in the ground.

In the absence of personal praise for this wood, we will report a use for which it is particularly intended in certain places. The stones, from which millstones are made, need to be of approximately constant thickness: here is how we manage to give them this dimension. We form, in the quarry, a column as high as the bench allows; then, with special tools, we surround this column in as many places and circularly as we want to find millstones there. When this groove is 6 or 8 lines deep, the millstones are separated in such an ingenious way that it deserves the admiration of the man educated in physics and the observing philosopher.

We cut willow into strips, 1 inch or 18 lines long: we keep the children busy making thousands of corners; they are dried for a long time, but at a moderate heat, in an oven; then, with small mallets, we fill all the grooves that we have made in the column throughout its height, very close to each other; then, with a pump or otherwise, we water the column considerably all around, and consequently, the corners with which it is lined. All these corners, eager for humidity, absorb a lot of it, swell, and, acting as levers, cause each division to split into regular pieces, which are as many millstones. We dry these corners again, which are used several times.

THE ASPEN, fig. 3, is included among the white woods, which are not of great use in the arts. We make excellent wood for polishing with emery, tapped, or pulverized sandstone, because being very soft, this emery, or as an ingredient, penetrates its txahee, and forms a species of soft lime which polishes very well. Hard wood, and especially of uneven density, is less good, because the emery, entering less into the wood, presents to the piece being polished, more hardness, and consequently, is subject to scratching.

Once again, we will somewhat avenge Aspen for its apparent uselessness, by saying that it is the only wood that shoemakers use to screw ankles into heels; hard wood, as it dries, would leave its place, whereas wood that is so tender, swells considerably, perishes from the slightest humidity, and still holds up well. A distinguished artist in the arts, the late Dom Bedos, author of The Organ Maker, and an excellent Gnomonic, had taught us a very simple way to iron razors, which was a perfect success for us.

We form a kind of razor leather from Aspen wood, having its
two surfaces a little behind a donkey. We coat both with fine grease, such as ointment: or sprinkle them with water emery, of the finest finesse, and we thus supplement the use of razor stones. which, however fine they may be, do not sharpen fine enough. We can assure that, by this means, the same razor held us tight for more than four years in a row, and that at the end, the curvature, which the grindstone gives to the blade, was almost entirely erased. Razor leathers are nothing more than powder, which serves to sharpen the edge; but when you press the razor on the leather, it necessarily makes this leather, which is soft, give way, which gives the edge a curved shape on each side, instead of wood, which does not give way, retaining the two surfaces of the razor well flat, and consequently, gives a more acute angle than the union of two curves.

THE BIRCH, fig. 4. is still among the white woods, and is used for the same purposes. It is a little harder than aspen: we know of few uses to which it is employed in the arts. Its branches, the. smaller, used to make brooms; and a custom that we hope to see disappear, causes unthinking parents to use its branches to imprint wisdom on their children.

ALDER, fig. 5, is still among the white woods, but its use is quite extensive in the arts. The turners, in common works, make chairs, stools, small beds for the children; and as this tree grows very high, and runs very straight and very small, ladders are made of the greatest height, such as 30 to 40 feet: the two heights are so flexible that when we see a man there going up, one cannot help but feel a feeling of fear for one's life, seeing it swing considerably. Masons also make eco-poles to scaffold houses and rise to the greatest height. We also make some small tower works.

THE LIME TREE, fig. 6, is still a white wood: it is known in gardens by. the shade it provided, early in the spring. Its flower, taken as an infusion, is an excellent emmenagogue. Its wood is soft, but it is used for different works for which the others are not suitable. It is a little more compact, and as it cuts quite cleanly, we make sticks of it to be gilded, and especially sculpture. It is not very prone to knots: it therefore works quite well with a plane, and is very pleasant to turn. It is cut into long, thin shavings which are used to make women's hats known as "chapeaux de paille blanche'.

The CHERRY TREE, fig. 7, which is confused with cherry, because they both have the same texture and the same bark, is a wood that turns very well, although a little soft to be used in large quantities. carpentry. We nevertheless make very pleasant pieces of furniture from it, particularly chairs, which, when passed through lime water, acquire a brown color, more solid than that of other chair wood which is dyed in all colors, and which change considerably over time. after some time. This tree has this singularity, that the bark, instead of being lengthwise like all the others, is crosswise, and seems to hold the wood in a kind of prison which opposes its growth. Also the people of the countryside, who have cherry trees, and who want to give them a faster growth, slightly split this bark on the north side, so that the split is not exposed neither to the heat of the south, nor to the rains. from the sunset This split soon increases to the point that the tree itself is, in a few years, split to the heart, and perishes in less than 12 to 15 years: but the wood is sacrificed to production.

THE PLUM TREE, fig. 8, is a tree that everyone knows; but we hardly work except the wild plum tree, that is to say, the one which comes, in the forests, without cultivation and without grafting. It is soft, binding, has fine grain, and works very well with a plane and lathe. As it is pleasantly veined, we can make little jewels from it, both in carpentry and on the Lathe. The bark of this wood is not a sure clue to define it or to recognize it: almost all wild fruit trees have the same bark; and it must be very practiced to recognize them externally. It is only their texture, their fibers, their color, their veins that . distinguish utis from others. We can even say that the Plum tree resembles the elm, by the way in which its veins are laid out, and by their color; but we barely notice its pores, whereas in the elm, they are very sensitive.

THE APPLE TREE, fig. 9, is a tree that grows low. It is prone to rolling, that is to say, twisting on itself, so that its wire is not often straight, which makes it quite difficult to cut with a plane; but, when it is healthy, it is a very pleasant wood to work with. It is hard, binding, tight, resembles the cormier in its redness and its veins. They are made into good carpentry tools of all kinds, and especially molding tools. It also works well on the Tour, and it is already one of those of which we will make a more direct application to the object which concerns us more particularly. When it ages, fairly large and white worms are introduced between the wood and the wood, which eat the intermediate substance, and which sometimes penetrate into the wood. If this ari>re did not have the disadvantage of being rolled and split, we would give it precedence over several others of which we are going to speak, and which are precious for the arts. The engineers of mills and large machines search for it carefully to burn your teeth or light the big wheels, and the rollers of the lanterns.

THE PEAR TREE, fig. 1, Pl. 3, is, in the judgment of workers, artists and amateurs, the most pleasant wood for all the arts. It is soft, binding, without knots or cracks, very smooth, very even, has a fine grain, can be planed, cut and turned in all shapes: it is also used to make models of machines. It is good for wood engraving, and it is it is used by wallpaper and Indian wallpaper manufacturers to make all their designs. It is not very hard, which means that it cannot be used for carpentry tools; but it has so many other qualities that we can easily overlook this slight flaw.

THE MOUNTAIN ASH, fig. 2, is a forest tree, which grows quite high, and which produces alises, a red fruit good to eat. Its bark is a color between that of hornbeam and that of oak. When it is felled and dry, the bark is easily detached from the wood; and as soon as it has passed a winter and a summer, it is advisable to remove it, since large white worms enter it which first eat the intermediate substance, and then introduce themselves as far as in the heart.

This wood seems to us to combine, to the supreme degree, all the qualities that a turner-mechanic can desire for his work. When it is young, it is white, soft to the plane and TdDr, veined almost like walnut, but whiter, and it has incomparably finer pores. When older, it is reddish, acquires hardness, and for this reason, is suitable for all the works for which we want to use it. Soft like pear wood, it planes as well as it does, and turns better, because it is tighter, and it can support fine moldings and pines. This tree grows high enough and big enough for us to have large pieces. We cut it into tables and boards. It is the best of all woods for making screws of all sizes. If the die cuts well, the screw will come out clean and smooth, as if we had taken the trouble to polish it. Black veins of the greatest hardness are often found in the heart.

In Paris, where most of the firewood comes in trains, that is to say, by means of floating, it is quite commonly found in building sites; but something that has been floated loses a little of its quality: and it is even very common, with a beautiful external appearance, to find it heated at the heart. This defect comes from the fact that it was cut out of sap; and, in this case, either the log is pierced furthermore and turns into powder, or else it is lashed with white spots, which take away all its consistency from the wood. But that which comes among new wood is more often good. This wood is extremely sought after. The construction site boys take great care to set it aside to sell it, either in detail, to amateurs, or by the way, and at a very high price, although this sorting is prohibited by municipal police regulations. However, as one would have to buy twenty strips of wood to find seven or eight beautiful logs, sometimes more, and often not one; that besides, it is a shame to burn it, it is necessary that, to provide the means of providing for it, sorting be tolerated.

The Toumenrs also make excellent mandrels for the Tour en l'air; and although some are made from boxwood, which are even harder, the most ordinary use is to take Mountain Ash.

We dwell with complacency on the praise of this wood, because in fact it is the one which brings together the most qualities for all the arts it also takes very well re-brown dyes, like the color of mahogany and others, which we will teach later.

SERVICE TREE, fig. 3, is placed, by some workers, above the aliner, in certain views. It is a forest area which grows quite large, and which produces corms, a type of small wild pear. It must be admitted that Service Tree is harder and taller than Mountain Ash: when it is old, when it is at least a certain size, we find, at the heart of the tree, red-brown veins. , which make it extremely heavy and hard: this is why we make, with this wood, the best menniacry tools, and particularly molding tools which are very useful. But, as it is prone to torment, the carpenters stick to the barrels of oak tools, (this is the body of the tool), small strips of Service Tree, on which they control the profile. molding, and use it as a tool that would be entirely Service tree.

ACACIA, fig. 4, is a very common tree. Naturalists distinguish between two kinds: the true one, which is quite rare, and the false one which they call Pseudo-Acacia, which is very common. Its wood, which is greenish-yellow, is only intended for the Tour. They are made into good bed casters, and mortars for pounding different materials, either in the kitchen or in the pharmacy. We also make pestles from it, and different pieces of tower, such as boxes suitable for wetting the tobacco, the spoon, the small stick which has a ball at one end to mix the tobacco. This wood is fine, soft, quite hard, and polishes very well.

THE DOGWOOD, fig. 5, is a small forest shrub, which rarely acquires more than an inch and a half or 3 inches in diameter, but which, ordinarily, has little more than one. This tree grows quite tall; but it is bristling throughout its length, with an infinity of branches, not very far from each other, which means that we frequently encounter knots that are quite strong, very hard, and. which interrupt the grain of the wood, so that little use can be made of it. It's a shame, no doubt, because it is white, fine, hard, without visible pores, and resembles duhoux in many respects. We make the best hammer handles, cart sides, and excellent rungs from it. It is very^wn to turn for small objects; but if we encounter a knot along the length of the piece, this knot is visible by a small black dot, which is infinitely hard. The fruit of this shrub is called Horn - It is as big as a cherry, and red like it.

THE HOLLY, fig. 6, is the strongest of the shrubs that our forests produce. It is green all year round; its leaves armed with quills, alternately inverted above and below, seem to defend the approach; and yet the wild boars will wallow there with pleasure. This shrub commonly comes as a bush. The skin of the young branches is a very beautiful green, when it is in its sap, and serves to retain the glue. The large branches are spotted with gray and large mossy greens. This wood is very fine, the most beautiful white possible, without visible pores, takes the most beautiful polish; and among other uses, it is used to make the white squares of checkerboards. It contains a large quantity of vegetation water, and retains it for a long time, which means that it takes a long time to dry; but when it has reached parity dryness, it yellows a little, and shrinks a lot. It is difficult to plan, except with a toothed plane, standing or with two irons: but it turns parËiitemeat. When a piece is finished at the Turn, one would be tempted to take it for ivory, because of certain small marks with which this wood is whipped, and which resemble those of ivory which is not very fine. Cabinetmakers make the greatest use of it, because of all the qualities that we have just detailed.

THE THORN, fig. 7, is very common in forests, and especially in hedges; but the one that grows into a tree is less ordinary. It is a very hard wood, less beautiful white than holly. Its grain is also much less fine. It looks quite similar to charm; but it is firmer. It is very bondable, and can be used on an infinity of works that we want to preserve in their whiteness. We see, by its growth, that it is a wild tree. A singularity of this tree is that there are many points and small branches in all directions which interrupt its thread when it is young. All these knots disappear entirely when it becomes large, unlike the common tree which always retains them, at some point. age it reaches.

THE SPINDLE TREE, fig. 8, is a wood which resembles, both in its bark and in its color and texture, French boxwood. It is with this wood that we commonly make the king's feet which we sell so cheaply, and which are only so common because they are marked and graduated, by applying them between two molds or caliln-es, where all the divisions are marked, and which are imprinted in the foot, by means of strong pressure: LeFusain still has a particular property: it is that, if we enclose a stick in a gun barrel, closed hermetically at both ends, with tampons, or with loam, and when we rub the barrel red along its entire length, we remove a spindle tree very suitable for drawing, and which has the property of being erased immediately, and without leaving a trace.

THE BOXWOOD OF FRANCE, fig. 9, is a shrub that does not do well in several of our provinces: it is what we call, in agricultural terms, very stunted, that is to say, very gnarled, twisted “and rarely quite straight. Perhaps these defects come from the fact that no care is taken of it, and that, intended to serve as a hedge as a hedge, we allow it to grow at random, and throw out an infinity of branches from the bottom to top. What grounds this conjecture is that there has long been a Boxwood in the Jardin des Plantes, in Paris, which grew to 10 or 12 feet high, and which, having become quite large, appeared to be open. of these frequent knots and this tortuosity which usually characterize it. It is a greenish-yellow color and planes quite poorly; but it turns well. There is no wood that supports the lathe screw as well as boxwood; and as long as the comb cuts well, the screw and nut are of a sharpness and cleanliness that nothing comes close to. As this wood is very hard, excellent mandrels can be made from it, especially those which should only be of mediocre size.

By a very natural consequence, of the fact that the Boxwood comes to France without care and without cultivation, it is ordinary to find excrescences in it {woven from a sap which has been expelled, and which over a long time produces an infinity of small sprigs, which could not produce enough growth to form decided branches. These growths, which we call Loupes, and. which come close to the ground, present natural accidents, sometimes very pleasant. These magnifying glasses, of which we have represented a slice, to give an idea, because of their infinite variety, are perfectly worked on the Tour. They come particularly from Saint-Claude, in Franche-Comté. We give them different dyes, which, insinuating themselves into the pores, or, to put it better, into the intorvaties' which each little eye lets oint its neighbors, and, combined with the yellow color which these burls take from the nature of the Boxwood , have a very good effect. The inhabitants of Saint-Claude send, to Paris, an infinity of works made with magnifying glasses, and put on them a very fine and very hard varnish, which Mr. Hamdin-Bergeron obtained, and of which he is still provided. We will give, in a separate chapter, how to use all the varnishes.

The burls are subject, the moment they have been worked, to reveal cracks or cracks which do not penetrate very far, but which sometimes cross the top or the sides of a boot. We clean these little slots perfectly; we form with a penknife, or otherwise, small corners which we glue into it, and which, by filling the hole or the slot, present new singularities, which we can increase at will. These magnifying glasses are also available at all times in the indicated store. There are people who claim that they are the roots of boxwood, and others, of olive trees; but it's a mistake.

There is another species of Boxwood infinitely superior to this one, it is the one that comes to us from Spain; but, so as not to disturb the plan that we have drawn up, we will talk about it in the chapter on foreign woods.

THE MULBERRY, fig. 2, by its color, its veins, and its grain, resembles acacia; but it is a little less firm, although it has a certain stiffness which makes it quite difficult to cut at the Tour. Moreover, as this wood is rarely used in the arts, we only mention it here to make it known to people who would not have the opportunity to have it before their eyes.

THE APRICOT TREE, fig. 3, is known to everyone, but few people have the opportunity to know the interior of the trunk. It is quite pleasantly veined, if it turns passably; but it does not work well with a plane: as it is difficult to obtain a good healthy one, and it can only be used for masonry work, we will say nothing more about it.

The Yew, Fig. 4, is a wood which grows everywhere, but which is little cultivated today. It's a shame that this tree comes so slowly, and grows so little, because it is very pleasant. It planes quite well, provided it is used with suitable tools, because of the frequent knots. There is no one who does not prefer it for one of the most beautiful woods on the islands.

The yew burl fig. 5, presents a quantity of veins intertwined with each other, which, on a snuffbox, produce a very pleasant effect; but these magnifying glasses are spoiled by an infinity of defects which hardly allow one to find a somewhat beautiful box cover. It is up to the amateur to use his patience to split or have these burls or breeches split with care, to get the best possible use out of them. This wood is capable of the most beautiful polish.

THE ORANGE TREE, fig. 6. It is natural to allow ourselves to be biased in favor of objects which present to our eyes certain qualities which please us. There is no one, perhaps, who is not convinced that the wood of the orange or lemon tree must contribute to the good smell that its leaves and flowers exhale. We can judge that this wood presents nothing particular to the eye; 'it looks a little like charcoal, and its grain resembles that of hornbeam. It turns quite a bit, and also planes itself; but he feels absolutely nothing.

It is true that we are hardly able to obtain this wood in the state in which the others are, at least in the temperate or cold climates of France. Because, as the Orange Tree is there only for pure pleasure; that it is rare and quite expensive, we certainly do not dare cut down an Orange tree 8 to 10 feet high, expressly to find in its stem, a few boxes or other objects: also we will agree that the section that We obtained to define it and to engrave it, that it was dead wood, and that this circumstance can totally change its nature.

THE WHITE MULBERRY, fig. 7, presents one of those varieties of nature, which penetrate more and more with the deepest respect for the creator, and for his least works. It seems that there should only be a difference between the white mulberry tree and the black mulberry tree in the fruit, and that at most, the wood should be a little browned. However, if we compare the two woods together, we will hardly find any very marked resemblances. One resembles the elm by its veins, which are infinitely close together; the other only resembles it from a distance, by the way in which the veins are marked on the bottom of the wood: but the grain, the color, the texture, the compactness, are absolutely different. The white mulberry partially supports the tenons and mortises. Its fibers are intertwined, its pores tight and all coming to the surface. We can hardly appreciate the real merit of the Mulberry tree, which is not common enough in all parts of France to be able to use it for many works: but it seems to us that, in the southern provinces , it could be used very advantageously to build furniture, such as chairs, tables, and other parts of the art of the carpenter-furniture maker.

THE JUNIPER fig. 8, seems to be considered only by the slight odor it exhales. As this shrub is of little height and size, we can hardly take advantage of it for the arts. Its wood is quite soft, but it is very fine, capable of a beautiful polish, quite pleasantly veined, and we can say that it hardly deserves the attention of the amateur, only a few small <^ ijcts that we would like to make in French wood, precious or unique. Many are found in the Fountainbleau forest, where juniper is very common.

THE EVERGREEN OAK, or holm oak, fig. 9, so named, because in fact it has some connection with the oak, and because it is grown all year round, differs so much from the tree whose name it bears, that no one will ever be tempted to confuse them. Green bean, of a certain size, not being very common, we were only able to obtain it in the office of a natural history enthusiast: we did not have the opportunity to use it in the Round.

Its bark has no relation to that of the diene. It is very thick and very brown. The wood fibers are quite fine and tight; but wood, in itself, is not infinitely hard. In no way can we recognize the texture of ordinary oak. However, it has the color; but the spots with which it is dotted, and which are different, depending on whether it approaches being on its mesh, or whether it moves away from it, make it interesting. It seems to us, however, that this wood can only be used as a curiosity by the Turner, to make some vase, pedestal, or other inconsiderable part, which, presenting the wood in all its directions and all the fibers and veins cut , will offer a rather pleasant singularity: if one of our readers wanted to see several of them, of a certain size, on foot, they will find them in the Jardin des Plantes, behind the hothouses, where they provide shade, at point of view that was practiced there with great art and talent.

THE OLIVE TREE, fig. 9, PL 6, is a very useful tree, and the source of the wealth of some of our southern provinces. It grows abundantly in Provence, Languedoc, Italy, and also in Spain. Olive wood is very well veined and has a rather pleasant odor; it takes a very beautiful polish, which makes it sought after by cabinetmakers and tablet makers: as this wood is resinous, it is excellent for burning.

The terrible winter of 1709, which caused the death of a large number of olive trees, gave occasion to notice that this tree grows a number of roots, and that they persist in the ground for entire centuries. In 1709, more wood was obtained from these roots than from the stems and branches of the trees; several owners sold them for more money than their stock was worth.

We have not claimed to give the nomenclature and description of all the woods that grow in France. We have only focused on the main ones, and especially on those which can be taken advantage of in the arts, and particularly on the Tour. It is for this reason that we have neglected several, which are not very useful, such as chestnut, whose fibers are so smooth, the cootexture so weak, that no advantage can be taken from it, as wood , although it provides the most beautiful shade in our gardens.

*** SECTION III Des Bois étrangers.

We do not intend to give the names, properties, and uses of all the woods which come to us from the islands, and from several other parts of the world: we will only report the best known in the art of Touring and in the cabinetmaking, in order to enable our readers to know them at least by their main qualities, and to use them for the uses they deem appropriate. Mr. Hamelin-Bergeron keeps an assortment of these different species of wood.

SPANISH BOXWOOD, fig. 1, Pl 5, is the most common of all foreign woods. He far outweighs the one who believes in France. It is full, plain, of a beautiful yellow, quite often of thread and without knots; hard, binding; and although it turns much better than it planes, or nevertheless gets quite good use of it with the plane, provided that some precautions are taken. We make boxes of all kinds; and, as this bcHs had time to dry before being brought to us, it works very well shortly after we have used it. We get logs four feet long or about: we have them of all sizes, up to five and six inches, and sometimes more. It takes on a very beautiful polish. It is with this wood that we make flutes, oboes, clarinets, and some other wind instruments. This wood is one of the two that are best cut with the chisel, as soon as we have acquired a little usual to handle it. It appears, from a passage in Virgil, that the Ancients knew the art of turning, and that they knew how to use boxwood as it should be, since this poet says, Georgics, book 2, verse 449:

Nec tiliae leves, aut Torno rasile buxum
Non formam accipiunt, ferroque cavantur acuto.

The lime tree, however, yields to the iron which hollows it;
The boxwood, according to the Tour, takes on a happy shape.

Thus, not only did the Ancients turn the wood externally, but they even hollowed it out; and, in this quote, we see tilewood and boxwood, two woods opposed by their nature, taken as an example of what can be done on the Tour. Virgil describes, in the seventh book of the Aeneid, the clog game that children play, and says that they were played with boxwood:

Ceu quondam tarto volitans sub verbere turbo, 
Quem pueri magno in gyro vacua atria circum 
Intenti ludo exercent. Ille actus habend, 
Curvatis fertur spatiis : stupet inscia turba 
Impubesque manus, mirata volubile buxum.
Dant animas plagœ. 

AENEID. VII 378. 

Such under the folding whip which whistles and pursues him,
Roll this spinning boxwood that childhood enjoys;
He runs, he goes, an immense portico comes back to me,
The young troop observes with astonishment
Del cerdes that he describes the agile movement,
Practice it without respite, and, the animator ceases,
By redoubled blows, redoubles his speed.

The Ancients made wind instruments with Boxwood: but it appears that these instruments were limited to flutes which they coupled together to extract sounds, which, no doubt, were in tune, in any harmonic relationship, like the third. ; otherwise, it would have been an unbearable cacophony:

Ite per alta 
Dindyma, ubi assuetis biforem dat tibia cantum. 
Tympana vos buxutque vacant Berecyntia matris 
Idaeae
AENEID. IX. 617. 

Go on double sound of your Trojan flute,
Cymbals of brass, of a melodious boxwood,
Celebrate in your groves your mother of the Gods;
For his laughing Dindyme or green penny Berecynthe
Leave our painful camps, leave the enclosure.

This quote proves both the seniority of the Tour and the degree of perfection it was. Others take it much further, and find its origin in the art of clay pottering, which, as we know, is very ancient.

ROSEWOOD, fig. 2, among the island woods is the most common. This wood is hard, purple-brown, has fairly sensitive fibers, and some more or less obscure veins. It is surrounded by white sapwood, which is very soft and is of no use. Rosewood gives off a fairly pleasant odor, especially when, when working with it, you heat it, and give rise to a certain evaporation. It is very easy to turn and plan: we can make an infinite number of small pieces of furniture from it; but as it is very obscure, it has been banned from large pieces of furniture, since nothing is so sad: the cabinetmakers know how to brighten it up by cutting it with other woods, and not entering it until as a report document. It is more commonly used in veneer, that is to say, in strips of a good thickness, which are glued to masses of oak or fir. As this wood is susceptible to a beautiful polish, and is hard, although porous, it does not take glue well: therefore the joinery assemblies, made of Rosewood, would not be solid. Moreover, the mortises, if forced a little by the right tenons, could burst. This wood is excellent for making hose reels, as we will describe them, and especially cases. It comes to us here in logs 3 to 4 inches thick, 9 to 12 feet long, and 12 to 15 inches wide. It is sold by the pound like all foreign wood.

PURPLE WOOD, fig. 3, is so named because of its color; but what makes it very pleasant are the more or less light veins which highlight the background: this wood is very hard, works equally well with a plane and a lathe. It has all the qualities and disadvantages of rosewood, which we previously discussed. There was a time when all the furniture was veneered in purple wood; another species of wood was brought to Europe, and from that moment the first was relegated to the antechambers, or to less fortunate people, as always happens when fashion has decided. It is, however, certain that this wood is very pleasant for a Turner. We can make an infinite number of precious objects from it.

EBONY is of several kinds. It appears that the black one was the first brought to France, since, although there are green or green-brown ones, and others brown, we say proverbially, black like Ebony.

BLACK EBONY,fig. 4, which is usually called Ebony-Maurice, is commonly the most beautiful black, it is capable of a very beautiful polish. It is more usually used in veneer. It cannot be fitted with tenons or mortises. When we prepare it with an axe, we are quite surprised not to make any cracks, like all other wood, but to see the hatchings come off in fragments which break, and do not have any damage; with the rest, no adhesion. We cannot make the nature of these fragments more perceptible than by saying that it seems, when we chop black ebony, that we chop, not quite coal, but wood which would have been half-consumed in the fire, or perhaps in the water; which leads us to suspect that this wood loses part of its natural consistency, due to the time it spends after cutting it, and before bringing it to Europe. It is very prone to being split: so the merchants are careful to keep it in very convenient places. The pores of this wood are very tight; we see no veins in it, and we can barely distinguish the direction of its fibers. It turns perfectly. Joined to ivory, or to some white wood, such as holly, which is very fine, it produces a very beautiful effect; it is subject to being lashed with dirty white or gray spots which discolor it; the workers dye them black, and then polish them,

PORTUGESE EBONY, fig. 5, looks much more like wood than the black one: it is only a dark brown. We can clearly see the fibers and pores. Under the axe, the shavings rise like all other wood. It is very hard, and consequently takes on a very beautiful polish. This wood presents a particularity common to many others: we see there sapwood of a gray tending to brown, and which is hard enough and fine enough so that we can, in a few circumstances - tances, take advantage of it. It is called Portuguese Ebony, because it comes to us from the colonies belonging to the Portuguese, in the New World. It is much harder than black, which is only preferred because of its great blackness. .

GREEN EBONY, fig. 6, is so called, because in fact it is olive green. The nature of the wood is still much better characterized than in the two previous centuries. The veins are well marked by light shades which separate them. We also see a sapwood of an air-gray color, which appears to have a completely different nature than the bay itself; and who is good for nothing. Unless we are used to distinguishing wood, we are tempted to mistake green ebony for grenaidilla, to which it closely resembles, as we will be able to judge in a moment. Green ebony works wonderfully with a plane and a lathe. As long as one has acquired the practice of cutting wood well, all these island woods, having reached their hardness, come out almost polished after removing the chisel, especially for the small parts; we are only obliged to polish large ones, because of the inequality that the cuts of a chisel, the best used, can leave, and by the differences that the pores can cause. We can make excellent molding tools, for carpentry, with these two types of wood; as they contain a little gummy-resioeated substance, they slide more easily on the wood and are not easily damaged.

ROSEWOOD, or ROSEWOOD, fig. 7, is, without a doubt, one of the most enjoyable. The workers persist in calling it Bois de rose, although its name, which comes from its color, is Bois rose. It is moderately hard, very filamentous, the fibers are well linked to each other. It comes to Europe in logs, not in tables. He is prone to being rotten to the core. It was not more than 50 or 60 years ago that it was introduced to Europe, where its great beauty made it used for all kinds of veneer furniture. But, as it has the disadvantage of losing its color in the air in a relatively short time, it was soon abandoned. It is no longer used except by turners in small works, especially since mahogany, which we will talk about shortly, has taken its place. However, for several years, a very clear varnish has been applied to almost all the works made at the Tour which, by filling the pores, perfectly preserves the color without leaving any thickness. This method is a great preservative for all colored woods: it prevents contact with air from discoloring them, and gives them a shine that surpasses the most beautiful polish. We will give in the appendix the composition of this varnish.

This wood, when we saw it, plan it, or turn it, exudes an odor which is a little like that of roses. It is greasy under the tool, cuts well with scissors; but it spoils if you try to polish it with oil, and takes on a dull appearance. The safest thing is to polish it well with eao, and finish the polish dry. However, we still experience some difficulties in this regard, because the pink mud that comes out confuses all the veins in which it is incorporated, and gives it a false color, which only a little oil gives it. perfectly. To avoid either inconvenience, you can rub it with a slightly oily cloth.

We also make, with this wood, very pleasant little models. It supports the tenon well, but the mortises are prone to splitting, even if it is not assembled in Korea. It doesn't take the glue perfectly.

This wood is prone to having many large knots, of which great advantage is taken for veneer. To obtain more marked and more beautiful edges, it is split into strips at a slight angle; and all these nodes present nuances and sinuosities which are assembled in pairs or other symmetrical numbers, and which reassemble perfectly, being taken one on top of the other. Chi saw some decorative pieces in pink wood in Paris, which had the most beautiful effect.

GRENADILLA, fig. 8, is an excellent wood for turning. It is pleasantly veined with brown on an olive background. We see the sapwood, common to almost all woods. It is planed very well; and how very hard it is, the makers of instruments. mtttique make excellent flutes, which are preferred to those of ebony and boxwood.

Grenadilla can be used at the lathe, for a number of very pleasant works. It takes on the polish of an ice cream; and if it is not that its color makes it a little confused with acacia, which however does not resemble the grain, it would perhaps be more precious than it actually is.

LIGNUM VITAE, fig. 9, whose heart is brown and very hard, as we will say below, only resembles the sapwood of old wood when it is young. We only point out this particularity to confirm the general principle that young wood does not have all the characteristics which should distinguish it. We find, in this young wood, greenish nuances and accidents, which make it sought after. tablets to make different works. There are these woods which have no rusty color, up to at least four inches in diameter. It is only after a few years that the woods acquire their maturity and their perfection; and it is through the heart that this perfection is felt, because it is always through the circumference that the woods take their growth. This truth is particularly noted in the hazel, of which we spoke in the article from Bois de France. We quite often encounter, in the heart of the service tree, parts of an almost black brown, and of extreme hardness, although the body of the tree is almost white. 

BROWN LIGNUM VITAE, fig. 1, Pl. 6, is still an excellent wood, both for its fineness and for its hardness. The sapwood is distinguished by two very sensitive colors. Near the bark, this sapwood is yellowish white: further on, it darkens with dirty yellow, further obscured by an infinity of imperceptible black pores. Next comes the heart, which is olive-brown at first, and becomes lighter towards the center. This heart is weakly veined, and in a way that is particular to it. This wood is very hard, as good for the lathe as for the plane. They can be made into excellent grinding tools for carpentry. He himself. polishes perfectly, but with horsetail in water, because of the quantity of resin it contains. We receive it in quite large logs, so that we can find many pieces of a very large diameter. The variety of colors, which the sapwood and the heart present, Had a quite beautiful effect in the hollow or projecting parts.

In addition to the qualities that we have just spoken about, and which make him use excellent skills to Elect. casters for beds and other furniture, intaglio press cylinders, grinder's easels and pulleys for the navy, this wood is used in medicine, as a sudorific.

SERVICE TREE OF THE ISLANDS, fig. 2, closely resembles that of France, except for the corridor, which is much darker. This wood is very hard: it is good for making tools. It sharpens partially, and takes on a very beautiful polish. Its veins are more marked and more frequent than those of the European cormier. He has little harm; but, despite this, the heart, whose color approaches that of ebony, is always a little harder, and the pores are tighter than around the circumference. In general, Cormier des Iles is little used in France, and it would benefit from being known.

MAHOGANY is of two kinds: soft and hard. Tenderness is rather little esteemed. In Paris, they are made into common furniture, which people, who do not know anything about it, accept indiscriminately because of the name.

The English were the first to use this wood for furniture. The extent of their trade in America makes it so common in England that it is used as joinery wood in an infinite number of circumstances.

Mahogany has since become, in Europe, the most sought-after wood for

furniture, necessities, etc. , etc. We receive colonies in balls, that is to say, in large pieces, some of which are up to 3 feet square over a length of 15 to 20 feet. The cabinetmakers, who buy and buy, are very uncertain about the quality it will have, since they can only know it fully when it is split at the heart, and they cannot obtain this condition from their sellers.

Hard Mahogany is of two kinds: one veined, fig. 3, and the speckled, fig. 4. Mahogany, in general, is a reddish yellow when newly worked. It browns prodigiously in a short time, and finally becomes an almost black brown. The way to polish it, when it has been well worn, is to rub it with a pumice stone and oil, then to absorb all the oil by rubbing it with a piece of cloth and washed tripoli, until the tripoli remains very dry, and then varnish it, as we will indicate for all wood; this is the only way to delay its browning: a layer of lime water makes it purple, but this color is not long-lasting. In furniture, this wood, being quite hard, is very good, because it stains little, and keeps its polish well. But, used on apartment doors, as among the English, it spreads into the rooms a darkness which inspires sadness, and which French gallantry and elegance would have difficulty adopting, unless your fashion decided otherwise. . This wood is veined with brown, and even black. Sometimes the knots give it a changing and shimmering air, which has a very pleasant effect. It planes wonderfully; but as it is often knotty or wavy, he had to plan it with a small iron, or with a double iron planer: without this, you instantly think you are finishing a piece, you get quite deep chips. It turns quite well; but he must be very master of his chisel to cut the threads of the wood. The most beautiful is the one which, on a light background, offers dark veins; and nevertheless it is necessary to have a very great use, to know if it will subsequently become beautiful: because, when it is newly split or planed, it is difficult to judge what it will be.

Speckled Mahogany, fig. 4, is quite rare. It sells for much more than the other; but, used on cabinetmaking panels, it is of great beauty. It’s the louse that detaches your flies from the bottom; for, when it is fresh cut, these moudies only seem to be slight waves, and do not. to great effect. The only way in which we can recognize it is to see if, at the circumference, we notice any kind of wormholes.

There is a third species of hard Mahogany, of which we cannot give a figure: it is Mahogany caught in tree breeches, and which is in large trees what boxwood burls are in small: The workers call Brambles these pieces thus split, to a line or approximately, in thickness. We cannot describe the infinitely precious accidents that these rare pieces present; it is chance that provides them. We saw some which represented trees, which one would have thought painted with the greatest art. Others represent a countryside, a landscape; and, in this case, we split them in pairs, and we place them in opposition to each other, to repeat. the same image. But unless you buy these pieces from wood merchants, an amateur cannot hope to find them, unless it is used by chance, since, for furniture of the highest price, the workers are forced to feel an infinite number of planks.

Finally, there is another species of mahogany, which is called bastard mahogany, and which only resembles the real one in color. but it is very compact, very hard, and contains more resin. It is excellent to turn, the same color as that which is freshly cut; and it has the advantage of retaining its color and not blackening like all other species.

Mahogany is a species of American walnut. Its fruit, which is eaten lightly toasted, resembles halves or quarters of ordinary walnuts, and is very good.

THE GUADELOUPE WALNUT TREE, of which fig. 5 represents a portion, is a little-known wood. We do not know what its fruit is, but the wood has no resemblance in grain, color, or porosity to the common walnut. It is quite hard, turns and planes hard. GOOD. Its yellowish color, veined with more yellow, can have, in some circumstances, a fairly good effect.; but this is only a fancy piece of wood to vary a few pieces.

AMARANTH, fig. 6, owes its name to its color. It is quite hard, takes a nice polish, turns and planes very well; but its pores are not very tight: it produces a very beautiful effect when, in cabinetmaking, it is intelligently opposed to wood of a different color. We can say nothing about the way in which it grows, nor about its fruit: we only know it as being suitable for cabinetmaking and turning.

CEDAR, fig. 7, is a very well-known tree, by all that ancient authors have said about it, and by the properties given to it: the Cedars of Lebanon grew to a prodigious height: they made the framework of the Teraple of Solomon; but it seems to me that this is not the Cedar we have today. We see one in the Jardin des Plantes, which has already grown considerably, and yet it is possible that the difference in climate is detrimental to its growth. Cedar is quite similar to beech, except that it is much darker in color, and the pores are finer. It is soft, and for this reason alone it is not very suitable for construction, unless it has been used, as we use these long fir trees today, to make floors of a fairly large span, but which don't wear anything. Cedar has an aromatic smell, which distinguishes it from all your woods, even from two that have an odor. It is perhaps for this reason that it is attributed the property of being incorruptible, and of not being attacked by any insect. The smell of cedar is such that if one had any piece of furniture in an apartment, it would not be possible to stay there for long. Furthermore, it works wonderfully with a plane, and turns well, although very fragile; and if out of curiosity we wanted to select some piece of Tower, we could get to the end with great caution: but the main use of Cedar is to serve as an envelope for pencils.

CITRINE SANDALWOOD, fig. 8, closely resembles cedar. It is of an absolutely similar color, but its fibers are very different. It doesn't have more density. It gives off a very strong odor, but which cannot be confused with that of cedar. That of Sandalwood is intoxicating, and displeases until the end. This wood planes very well, and turns better than cedar. It is called Citrin, either to distinguish it from the Santal den which we are going to talk about, but because its smell is a bit like that of lemon. It is very fine, susceptible to a fairly fine polish, very soft to the touch, and its pores are very fine.

WHITE SANDALWOOD has no relation to the previous one. It is much more yellow than white. Its pores are quite fine, and tighter; and, if it resembles any wood, it is certainly the European chestnut, even in the bark, except that it is finer, harder, and is capable of real polishing, it works very well with a plane, and turns quite well. Furthermore, it is one of the woods that we use to vary objects, contrast colors with colors, and bring together, in the same place, all the varieties that nature offers in its productions.

THE SASSAFRAS, fig. 1, Pl. 7, seems to be more of a spongy substance than wood proper. Its pores are very loose, its fibers very coarse. It doesn't have a thread. Its bark is quite similar to that of the beech: it planes quite a bit, because it is very soft; but it is very difficult to turn, because of this very softness. It has a lightness which surprises at first, but which no longer surprises us as soon as we consider it, and we recognize in it the qualities by which we have just characterized it. This tree grows large and very branchy: it grows in Brazil, and in several other places in America. Its wood is used medicinally, as a sudorific and diuretic. It exudes a fairly strong odor, which makes it stand out from all the others.

Ordinary SATIN WOOD, fig. 2, is most pleasant, especially for cabinetmaking. Placed in opposition to other woods, it has the most pleasant effect. Apart from its color, and judging it only by its fibers, its pores, its density, we would take it for walnut which had been dyed, if it could be dyed in a light color. It is duck-yellow, and its pores, which seem like a pigeon's throat, give it a very pleasant change, depending on the light in which it is seen. It planes perfectly, and turns in absolutely the same way as walnut, to which , apart from the color, we can assure that it resembles everything.

YELLOW SATINWOOD, fig. 3, has no resemblance to the previous one. It is quite dark yellow, and veined in a few places. Its grain, its pores and its threads make it quite similar to white or Ruroit dyed saltwood, and on which natural veins would give, in some places, lighter or darker parts. We saw a boudoir in a library, where, under rather poorly observed rules of architecture, all the members had been fitted with wooden moldings of different colors: nothing was as beautiful, as imposing. t as rich. The parquet floor itself was a mosaic of different woods, used with taste and intelligence; and you saw, with pleasure, that all parts of the world had been called upon to decorate a reduced canopy. The columns were of yellow satin; the friezes of an opposite wood; red satin or coral denticles, etc. , etc. The cedar served as shelves; and the bases and other lower parts were of the finest mahogany.

Yellow Satinwood planes and turns perfectly. It comes to us in large enough logs, so that we can use it for whatever we want: but what is singular about it is that small worms, starting from the circumference, insinuate themselves until 'at the heart of the wood, and reveal pitting right up to the very front of the most beautiful pieces.

THE RED SATINWOOD, fig. 4. couldn't be more pleasant; but as its veins are very small, and the lines which form the satin are very fine, - it must be seen very closely or be used for small works. It is the most beautiful purple possible, veined with brown. He is very hard; takes a beautiful polish, works equally well with a plane or a Toiir; but once again, when we look at it from a little distance, it only looks like wood, which would be a very beautiful solid red; This wood is undoubtedly one of the most beautiful that the New World provides us.

THE COCONUT, fig. 5, is a wood which comes in all the lees of America. All naturalists agree that it seems that the Creator wanted, in this tree, to give travelers all the gifts at once. Its fruit is the size of a mediocre melon. The husk of this fruit is filamentous on the outside; but soon we discovered a very hard substance, capable of the finest polish. Internally this hull is very polished. When we open the fruit, a milky water comes out, very sweet, and which refreshes. The fruit is excellent to eat. The tree produces very nice shade. The species of hemp which surrounds it can be spun and form a fabric suitable for clothing.

Coconut wood contributes to the hardness of the fruit. It is very hard, very tight and very compact. It is not very veined: its fibers, although not very tight in appearance, are, in fact, very tight: we can judge this by the weight of the wood. It planes and turns perfectly; but, as its colors do not have much vibrancy, it seems to be only dyed wood. A table, made of Coconut, would have the very rare merit of not being able to be easily penetrated by colored liquors, which happens too often to the mahogany tables, which we use now.

MANCHINEEL, fig. 6, is a wood of a dark yellow and tending to brown. - 11 is veined and waves almost like maple, which it closely resembles; but it is much harder. It carries in the waves, some; clear which have a very pleasant effect. This wood is capable of a fairly nice polish. It planes very well, and turns just as easily. Nothing is as beautiful as a piece, made on the Lathe, with this wood: the veins and the waves are multiplied by the different cuts, which are highlighted by the bulges and the hollowed parts. If we take care to garnish these vases with ivory, as well as those made with almost all Indian woods, the veins, the waves, stand out more.

CORAL WOOD, fig. 7, is a wood which was given this name because of its superb coral color. It is indeed of the most beautiful age; but it has this singularity, that when it is cut or split, the part which is exposed to the air is yellow, and turns red in quite a few tenqis. This phenomenon can very well explain the influence of air on colors; and physics has already learned that a liquor steeped for a long time changes color; and this experiment was carried out on the spirit of wine of a thermometer, which, from red as it was, became barely slightly tinted. Chance would have broken the tube, and immediately the liquor regained its original color.

The coral is very fine, very hard, and therefore susceptible to a fine polish. It also works well with a lathe and a plane. But it can hardly serve, in either case, other than to highlight other parts, given that the uniformity of its color does not present anything very satisfactory to the eye.

Damask Coral, fig. 8, is much more valuable than the previous one. It is thus named, because in fact its veins are arranged in the same way as damask linen. It is a red (juice brown) and light in color, with the damask pleasantly highlighting its waves. Although less hard, very thin and more porous, it turns perfectly. It is also worked well with a plane: it is certainly one of the most pleasant planes in India; but it is quite rare. It has the most beautiful effect in the works of Tour, where the round parts, opposed to the hollow parts, multiply the waves and the damassores, and give birth to an infinity of accidents of the greatest beauty.

PARTRIDGE WOOD, fig. 9, is yet another species of very hard wood, which can be confused at first glance with rosewood, but which is much lighter, more compact, and consequently heavier. In addition to the perpendicular fibers, there are transverse ones, which one would believe drawn with a ruler, so regular are they. The opposition of these fires produces, on a piece made at the Tour, very piquant and

the most pleasant. It planes perfectly, turns in the same way, and takes on a beautiful polish: it has no very marked veins; but we see there an infinity of small gray-brown flies, which have given it the name of Wood, of Partridge. Its fibers are similar to those of rosewood. The entailtists cut it obliquely to its grain and with great skill, as well as almost all the woods of which we have spoken, to further highlight their veins, and the accidents which are encountered there.

VEINED JASMINE, fig. 1, Pl. 8, is infinitely hard, dark brown, veined with small flames. All these woods have their sapwood more or less sensitive, more or less beautiful, depending on whether it approaches its state of perfection; This is what we can notice in this one. It cuts perfectly, and is also suitable for the lathe and the plane. They make excellent rules and other mathematical instruments. None of the woods of the islands can be characterized by their bark, seeing that as the freight to the sea ports, and the transport, by water, from the port to the capital, are very expensive, it is useless to bring, to Europe, a part which should not and cannot be used for anything, and which he would have to throw away when he arrived.

SPECKLED JASMINE, fig. 2, is roughly similar to the previous one, except that the speckles are more decided. It is just as hard and as thin as the previous one. You can hardly see the pores. The sapwood is arranged in the same way. It polishes perfectly, turns and planes equally well. We make violin ardiets of both; and, by its singularity, and by its beauty, we can create an infinity of very pleasant objects and thus diversify a work in which we wish to vary the woods to infinity, to enhance each other.

SNAKEWOOD, fig. 3, is a third species of wood from China
It is very fine, very compact and very hard. H couldn't be more pleasant in cabinetmaking, where it produces the most decided effect. It planes and turns well. Its veins are thrown in different directions, and present very interesting plays of nature, depending on whether it is used or cut. The different shades that it offers to the eyes, from pink to very dark red-brown, arranged with art, can stand out from other woods that it frames, or with which it is placed in opposition. It is the same for the works of Tour. We can make vases or other turned pieces from them, and garnish them with wood opposite in color, or in ivory; arrange the cuts so that the veins repeat symmetrically; in a word, it is one of the most precious woods that come to us from China.

SPANISH ELM, fig. 4, resembles, in many respects, somewhat pale boxwood. It planes and turns perfectly. It is very strong, very tight and very hard. Its bark resembles that of the small elm, a wood from France. But what distinguishes this wood from all others is that it gives off a very pleasant and very sweet odor. It is claimed that a little of this wood, scraped and put in a snuffbox, gives the tobacco the pleasant taste of macoubac.

IRONWOOD, fig. 5, so named because of its great hardness, is quite similar in color to rosewood wood, and in the way it is veined, to purple wood. It contains a very large white sapwood, which contributes to its great hardness. It is such that the natives of the Antilles used it, before the discovery of America, to make sabers, the wounds of which were very dangerous and often fatal. Although this wood is perfectly good for working with a plane and a lathe, it presents too few varieties for anything very curious to be done with it on the lathe; and we can say that he only has the merit of hardness, a merit that he possesses to a supreme degree. Also, the enthusiasts make rulers, squares, and carpentry tools from them, which are highly sought after, despite their cost. A guillaume, for example, who, to be good, needs to maintain his straightness, not to cut on any crooked wood, and to cut very finely, especially when we want to cut sharp corners. , is perfectly good in Ironwood.

BRAZIL WOOD, fig. 6, is a very dark red and tending to brown. It presents nothing spicy for the cabinetmaker, or for the turner. It is hard, tight, has fine pores> cuts and planes very well.; but it has qualities and properties that make it sought after above all others: it is with this wood that we make red dyes, more or less dark, depending on whether we add teb or such ingredients. , as we will say in a separate chapter. We cut it into small shavings, and we boil it in water: and so that the division of the coloring parts happens even better and faster, we grate it into curly and very small shavings; at least, that's how it is sold ^ in Paris, among certain grocers-druggists, in small numbers, who keep it.

LOGWOOD, fig. 7, is still a wood that receives little attention in the art of Turning, and in cabinetmaking. Its color is a fiery red; but its knots, worked and polished, create quite a beautiful effect. It looks quite similar, in color, to. mahogany which has not yet blackened. But this wood is used a lot to dye a beautiful red, as we will see in the chapter on wood dyeing. The stiffness with which it becomes bright red when thrown into boiling water, impregnated with a little alum, is surprising.

BRAZILWOODC, or, as the experts say, femambourg, fig. 8, is still a red stained wood. Being worked with a plane, or on the lathe, it perfectly resembles soft, slightly veined mahogany. It does not blacken in the air; it has fairly fine pores, takes polish well: but, as it is only used for dyeing, we will not say more.

We will end this article of the woods, with an object of pure curiosity, and which chance has placed in our hands: it is a small planchette, taken from a bush of a tree which we call Palm tree; we see two in the Jardin des Plantes, in Paris.

fig. 9, represents this species of wood, if we can say that it is one. It seems rather, considering it by its bark, and by its transverse section, that it is only a meeting of small filaments, adhering to the BUS aqx others, by means of a gray substance, which is of a completely different nature. nature, and which seems purely medulpheire. It planes quite well; but we didn't have the opportunity to shoot any. Considering it from its end, it resembles an infinity of rushes which are pressed against each other, and whose intervals are filled with wax of mediocre whiteness. We do not know what this wood could be used for, which we have only spoken of here because of its rarity and singularity.

** CHAPTER II Du Laboratoire.
